# Generated by Django 4.1.7 on 2023-02-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tarea_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Tasks',
        ),
    ]
